---
#-------------------------------

title: Angela Boakye Danquah
logo:
author: Angela Boakye Danquah
description: Angela Boakye Danquah's Porfolio Website
email: aab5zd@virginia.edu
copyright: Copyright &copy; 2023 Angela Boakye Danquah
menu:
  - { name: About, link: "/about" }
  - { name: Resume,link: "/resume"}
  - { name: Portfolio, link: "/portfolio" }
  - { name: Contact, link: "/contact" }

#-------------------------------

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: # UA-XXXXXX-X

#-------------------------------

disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown

#-------------------------------

hero:
  hero-title: Hi! I’m <br> Angela, <br> Data Scientist

social:
  - { icon: "ti-linkedin", link: "https://www.linkedin.com/in/angela-boakye-danquah-a28694194/" }
  - { icon: "ti-github", link: "https://github.com/aab5zd" }

#-------------------------------

blurb: Hi, I’m Angela — a data scientist specializing in large-scale data systems, applied machine learning, and analytical problem-solving. I’m passionate about turning complex datasets into meaningful insights and building robust, scalable solutions that support real-world decision-making. Learn more about my work below.

blurb-btn-link: "/about"
blurb-btn-name: Find Out More


#-------------------------------

skills-title: Skills

# Client Slider Section

client-slider-items:
  - logo: "assets/images/clients-logo/aws.drawio.png"
    url: "#"

  - logo: "assets/images/clients-logo/azurer.drawio.png"
    url: "#"

  - logo: "assets/images/clients-logo/dask.drawio.png"
    url: "#"

  - logo: "assets/images/clients-logo/excel.drawio.png"
    url: "#"

  - logo: "assets/images/clients-logo/git.drawio.png"
    url: "#"

  - logo: "assets/images/clients-logo/hadoop.drawio.png"
    url: "#"

  - logo: "assets/images/clients-logo/powerbi.drawio.png"
    url: "#"

  - logo: "assets/images/clients-logo/powerpoint.drawio.png"
    url: "#"

  - logo: "assets/images/clients-logo/python.drawio.png"
    url: "#"

  - logo: "assets/images/clients-logo/r.drawio.png"
    url: "#"

  - logo: "assets/images/clients-logo/spark.drawio.png"
    url: "#"

  - logo: "assets/images/clients-logo/sql.drawio.png"
    url: "#"

  - logo: "assets/images/clients-logo/tableau.drawio.png"
    url: "#"

  - logo: "assets/images/clients-logo/Untitled Diagram-word.drawio.png"
    url: "#"



#-------------------------------

education-title: Education
education:
  - {
      name: Master of Science in Data Science,
      date: "2023",
      organization: "University of Virginia",
    }
  - {
      name: Bachelor of Arts in Statistics and Economics,
      date: "2021",
      organization: "University of Virginia",
    }

#-------------------------------

portfolio-home-items:
  - image: "assets/images/portfolio/opioid.png"
    url: "https://aab5zd.github.io/Using%20Inferential%20Methods%20to%20Find%20a%20Link%20Between%20the%20Opioid%20Epidemic%20and%20White%20Supremacist%20Domestic%20Terrorism.pdf"

  - image: "assets/images/portfolio/recommender.jpg"
    url: "https://aab5zd.github.io/Collaborative%20Topic%20Modeling.pdf"

  - image: "assets/images/portfolio/genre.jpg"
    url: "https://aab5zd.github.io/DL%20Genre%20Categorization.pdf"

  - image: "assets/images/portfolio/glaucoma.png"
    url: "https://rc.virginia.edu/project/glaucoma/"

  - image: "assets/images/portfolio/ercp.png"
    url: "https://rc.virginia.edu/project/ercp/"

portfolio-label:
  - { title: "Music", type: "music" }
  - { title: "Deep Learning", type: "dl" }
  - { title: "Research Computing", type: "research" }
  - { title: "Other", type: "other" }

portfolio-items:
  - image: "assets/images/portfolio/opioid.png"
    url: "https://aab5zd.github.io/Using%20Inferential%20Methods%20to%20Find%20a%20Link%20Between%20the%20Opioid%20Epidemic%20and%20White%20Supremacist%20Domestic%20Terrorism.pdf"
    portfolio-type:
      - type: "other"

  - image: "assets/images/portfolio/genre.jpg"
    url: "https://aab5zd.github.io/Collaborative%20Topic%20Modeling.pdf"
    portfolio-type:
      - type: "music"

  - image: "assets/images/portfolio/recommender.jpg"
    url: "https://aab5zd.github.io/DL%20Genre%20Categorization.pdf"
    portfolio-type:
      - type: "music"
      - type: "dl"

  - image: "assets/images/portfolio/glaucoma.png"
    url: "https://rc.virginia.edu/project/glaucoma/"
    portfolio-type:
      - type: "research"
      - type: "dl"

  - image: "assets/images/portfolio/ercp.png"
    url: "https://rc.virginia.edu/project/ercp/"
    portfolio-type:
      - type: "research"

#-------------------------------


contact-title: Contact Info
contact-email: angela.bdanquah@gmail.com
